# Generated by Django 4.2.4 on 2023-09-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='HourLimit',
            field=models.IntegerField(default=0, verbose_name='小时限制'),
        ),
    ]
